[package]
name = "wysgy_core"
version = "0.1.0"
authors = ["Prasanna <srprajagopal@gmail.com>"]
edition = "2018"
description = "Core libs for wysgy, a command line graph DB"

[dependencies]
serde_json = "1.0"
prettytable-rs = "^0.8"
glob = "^0.3"
