[package]
name = "wysgy"
version = "0.1.0"
authors = ["Prasanna <srprajagopal@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
node_create = {path="../node_create", version="0.1.0"}
serde_json = "1.0"
